### Cloudflare API Documentation - https://api.cloudflare.com/#zone-settings-get-always-online-setting

@api=https://api.cloudflare.com/client/v4
@token={{$dotenv Cloudflare_API_Token}}
@status = active

@domain={{$dotenv domain}}


# https://api.cloudflare.com/#zone-list-zones
### List Zones - 用域名查出對應的 zone_id (域名操作需要它)
# @name list_zones
GET {{api}}/zones
    ?name={{domain}}
    &page=1
    &per_page=50
    &order=status
    &direction=desc
Authorization: Bearer {{token}}


### Zone ID
@zone_id = {{list_zones.response.body.result[0].id}}


# https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records
### List DNS Records - 列出 特定域名 的所有解析紀錄
GET {{api}}/zones/{{zone_id}}/dns_records
    ?page=1
    &per_page=200
    &order=type
    &direction=desc
Authorization: Bearer {{token}}


###
GET https://api.cloudflare.com/client/v4/zones/{{zone_id}}/dns_records
Authorization: Bearer {{token}}
Content-Type: application/json


###
@record_id=5be89e30ce97613b9acf93825faceeb9


### 改 proxy
PUT {{api}}/zones/{{zone_id}}/dns_records/{{record_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "type": "CNAME",
    "name": "www.weibyapps.com",
    "content": "weibyofficialwebsite-1818581912.us-west-2.elb.amazonaws.com",
    "ttl": 1,
    "proxied": false
}

###