# https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/

@instanceUrl=https://{{$dotenv jiraDomain}}
@APIv2={{instanceUrl}}/rest/api/2

@issueIdOrKey={{$dotenv IssueKey}}

@user={{$dotenv user}}
@token={{$dotenv token}}


### Get Issue
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-get
GET {{APIv2}}/issue/{{issueIdOrKey}}
Authorization: Basic {{user}}:{{token}}


### Get create issue metadata
# https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-createmeta-get
GET {{APIv2}}/issue/createmeta
Authorization: Basic {{user}}:{{token}}
Accept: application/json


### 
